apiVersion: 1

# delete old datasources before adding the new ones
deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://prometheus:9090
    basicAuth: false
    editable: true
    isDefault: true
    orgId: 1
