version: '3.8'
services:
  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node-exporter
    restart: unless-stopped
    user: root
    network_mode: host # to include host network interfaces in metrics
    expose:
      - 9100
    labels:
      observability_stack: "exporter"
    logging:
      driver: local
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /var/run/dbus:/var/run/dbus:ro
      - /run/systemd:/run/systemd:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.systemd'
      - '--collector.processes'
      - '--collector.interrupts'