version: '3.8'
services:
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    restart: unless-stopped
    user: root
    extra_hosts:
      - "host.docker.internal:host-gateway" # to access containers running in host mode
    expose:
      - 9090
    labels:
      observability_stack: "datasource"
    logging:
      driver: local
    volumes:
      - ./stack/prometheus:/etc/prometheus/
      - ./prometheus_runtime_data:/prometheus/data
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.size=1GB'
      - '--web.enable-admin-api'

  alertmanager:
    image: prom/alertmanager:v0.28.0
    container_name: alertmanager
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway" # to access notification server running on host
    expose:
      - 9093
    labels:
      observability_stack: "alertmanager"
    volumes:
      - ./stack/alertmanager:/etc/alertmanager
    command: 
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--cluster.listen-address=' # disable high availability mode

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    labels:
      observability_stack: "visualization"
    logging:
      driver: local
    volumes:
      - ./stack/grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./stack/grafana/grafana.env