# EXAMPLE: https://github.com/prometheus/prometheus/blob/release-3.1/config/testdata/conf.good.yml
# REFERENCE: https://prometheus.io/docs/prometheus/latest/configuration/configuration/

global:
  scrape_interval: 15s # scrape targets every 15 seconds.
  evaluation_interval: 15s # evaluate rules every 15 seconds.

rule_files:
  - 'rules/*.rules'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
  - job_name: 'python_app'
    static_configs:
      - targets: ["host.docker.internal:8000"]
  # for prometheus status dashboard on grafana
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']